language: php
dist: trusty

php:
  - 7.1
  - nightly

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E0C56BD4
  - sudo apt-add-repository "deb http://repo.yandex.ru/clickhouse/trusty stable main"
  - sudo apt-get update -qq
  - sudo apt-get install clickhouse-server-common clickhouse-client -y
  - sudo service clickhouse-server start

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit --configuration ./phpunit.xml.dist

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
